services:
  client:
    build:
      context: ./client
      dockerfile: dockerfile
    ports:
      - "3002:3002"

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "3001:3001"

  server:
    build:
      context: ./server
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://admin:pass@mongodb:27017/easyShopEcommerce?authSource=admin

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
